name:
    build-tauri-linux
on:
    pull_request:
        branches:
            main
permissions:
    contents: read
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v4
              with:
                node-version: latest
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - name: install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y libwebkit2gtk-4.1-dev librsvg2-dev patchelf #libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev
            - run:
                npm install
            - run:
                cp .env.dummy .env.local
            - run:
                npm exec tauri build

            - uses: actions/upload-artifact@v4
              with:
                name: artifacts
                path: "src-tauri/target/release/fairplay-app"
