name:
    check
on:
    pull_request:
        branches:
            main
permissions:
    contents: read
jobs:
    build:
        name: check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Setup rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - name: Install system dependencies
              run:
                sudo apt-get update
            - name: Install dioxus-cli
              run: |
                curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
                cargo binstall dioxus-cli
            - name: Check api
              run: |
                cd api
                cargo check
            - name: Check web
              run:
                dx check --package web
            - name: Check desktop
              run:
                dx check --package desktop
            - name: Check mobile
              run:
                dx check --package desktop
